# Generated by Django 3.0.4 on 2020-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_auto_20200328_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Thai', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='unique_identification_string',
            field=models.CharField(default='ac6a657db09446ffa6b42712307865f4', max_length=32),
            preserve_default=False,
        ),
    ]
