# Generated by Django 3.0.4 on 2020-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_auto_20200329_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_identification_string',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
